(executable
 (name lexer_golden)
 (libraries ash.core ash.syntax)
 (flags
  (:standard -w +a-4-9-40-41-42-44-45-70 -warn-error +8+11+26+27+32..39)))

(rule
 (with-stdout-to lexer.output (run ./lexer_golden.exe)))

(rule
 (alias runtest)
 (action
  (diff lexer.expected lexer.output)))

(executable
 (name parser_golden)
 (libraries ash.core ash.syntax)
 (flags
  (:standard -w +a-4-9-40-41-42-44-45-70 -warn-error +8+11+26+27+32..39)))

(rule
 (with-stdout-to parser.output (run ./parser_golden.exe)))

(rule
 (alias runtest)
 (action
  (diff parser.expected parser.output)))

(executable
 (name desugar_golden)
 (libraries ash.core ash.syntax ash.runtime)
 (flags
  (:standard -w +a-4-9-40-41-42-44-45-70 -warn-error +8+11+26+27+32..39)))

(rule
 (with-stdout-to desugar.output (run ./desugar_golden.exe)))

(rule
 (alias runtest)
 (action
  (diff desugar.expected desugar.output)))
