(** Hygienic identifiers: printed name plus unique identity.

    Lexical identity in Ash is never a string (AGENTS invariant 1). An identifier
    is a pair of a printed name, which exists only for humans, and an integer ID
    allocated once and never reused. [fn(x#173) -> x#173] and [x#42] both print
    as [x] and are different terms.

    Intrinsic hygiene follows by construction: a binder generated by the
    specializer or a macro cannot collide with a user binder even when it chooses
    the same printed name, and a quoted variable spliced under an unrelated binder
    of the same name still refers to its original binding.

    Reflective code that resolves variables by runtime string does not use this
    type at all; that is what the separate [NamedVar] Core node is for. *)

type t = private { name : string; id : int }
(** Immutable and private: every identifier must come from {!fresh} or
    {!Canon}, so ID allocation stays centralized and IDs stay unique. *)

(** {1 Allocation}

    All fresh IDs come from one process-wide counter. Its value is an excluded
    observation (AGENTS invariant 10): nothing semantic, and no test, may depend
    on the numbers it hands out. Compare identifiers with {!equal} and compare
    terms through {!Canon}. *)

val fresh : string -> t
(** [fresh name] allocates a new identity printed as [name]. *)

val derive : t -> t
(** A new identity with the same printed name, for renaming an existing binder. *)

val derive_as : string -> t -> t
(** A new identity printed as the given name, keeping [t] only as documentation
    of where the binder came from. *)

(** {1 Accessors} *)

val name : t -> string
(** The printed name. Never use it to decide identity. *)

val id : t -> int
val equal : t -> t -> bool
val compare : t -> t -> int
val hash : t -> int

val same_name : t -> t -> bool
(** True when two identifiers print alike, whether or not they are the same
    binder. Useful for diagnostics ("did you mean the outer [x]?"), never for
    resolution. *)

val to_string : t -> string
(** Unambiguous form, ["x#173"], for debugging and error messages. *)

val pp : Format.formatter -> t -> unit

module Set : Set.S with type elt = t
module Map : Map.S with type key = t

(** {1 Canonicalization}

    Structural comparison of terms containing raw identifiers depends on
    allocation order, which is meaningless. Canonicalization renumbers
    identifiers by order of first occurrence in a traversal, so two terms that
    differ only by renaming become structurally equal.

    Canonical identities live in their own numbering: slot [n] becomes
    [-(n + 1)], and every printed name becomes the positional [v]. Allocated
    identities are always positive, so a canonical identifier can never collide
    with one that {!fresh} handed out — which is what makes structural equality
    of canonicalized terms exactly alpha-equivalence even when a term has free
    identifiers.

    Soundness note: renumbering by first occurrence identifies alpha-equivalent
    terms only when the traversal visits both terms in the same order and every
    identifier that is {e free} in the term is registered with {!fix} first.
    A free [x#4] and a free [y#9] denote different variables and must not both
    canonicalize to the first slot. Binding-aware traversal belongs to
    {!Alpha}; this module supplies the renumbering it uses. *)

module Canon : sig
  type ident := t
  type t

  val create : unit -> t
  (** A fresh, empty renumbering state. *)

  val fix : t -> ident -> unit
  (** Map [ident] to itself, reserving it from renumbering. Use it for free and
      global identifiers before traversing a term. Fixing an identifier that has
      already been canonicalized raises [Invalid_argument]. *)

  val canonical : t -> ident -> ident
  (** The canonical identifier for [ident] under this state, allocating the next
      slot on first sight and returning the same result on every later call. *)

  val count : t -> int
  (** How many distinct identifiers have been renumbered so far, excluding fixed
      ones. *)

  val list : ident list -> ident list
  (** Canonicalize a whole sequence with a private state, left to right. *)
end
