type position = { file : string; line : int; column : int; offset : int }
type t = { start : position; stop : position; origin : origin }
and origin = Source | Generated of generated
and generated = { by : string; from : t }

(* Positions *)

let position ~file ~line ~column ~offset = { file; line; column; offset }
let start_of_file file = { file; line = 1; column = 1; offset = 0 }

let compare_position a b =
  match String.compare a.file b.file with
  | 0 -> Int.compare a.offset b.offset
  | ordering -> ordering

let equal_position a b = compare_position a b = 0

let string_of_position p =
  Printf.sprintf "%s:%d:%d" p.file p.line p.column

(* Spans *)

let make ~start ~stop = { start; stop; origin = Source }
let point p = { start = p; stop = p; origin = Source }

let unknown_file = "<unknown>"

let unknown =
  let p = { file = unknown_file; line = 0; column = 0; offset = 0 } in
  { start = p; stop = p; origin = Source }

let is_unknown span = String.equal span.start.file unknown_file
let file span = span.start.file

let join a b =
  if is_unknown a then b
  else if is_unknown b then a
  else if not (String.equal a.start.file b.start.file) then a
  else
    let start = if compare_position a.start b.start <= 0 then a.start else b.start in
    let stop = if compare_position a.stop b.stop >= 0 then a.stop else b.stop in
    (* The nearest enclosing generator explains the joined node best, so the left
       origin wins unless it has nothing to say. *)
    let origin = match a.origin with Source -> b.origin | Generated _ -> a.origin in
    { start; stop; origin }

(* Provenance *)

let generated ~by ~from =
  { start = from.start; stop = from.stop; origin = Generated { by; from } }

let is_generated span = match span.origin with Source -> false | Generated _ -> true

let rec source_span span =
  match span.origin with Source -> span | Generated { from; _ } -> source_span from

let generators span =
  let rec collect acc span =
    match span.origin with
    | Source -> List.rev acc
    | Generated { by; from } -> collect (by :: acc) from
  in
  collect [] span

(* Comparison and printing *)

let rec compare a b =
  match compare_position a.start b.start with
  | 0 -> (
      match compare_position a.stop b.stop with
      | 0 -> compare_origin a.origin b.origin
      | ordering -> ordering)
  | ordering -> ordering

and compare_origin a b =
  match (a, b) with
  | Source, Source -> 0
  | Source, Generated _ -> -1
  | Generated _, Source -> 1
  | Generated x, Generated y -> (
      match String.compare x.by y.by with
      | 0 -> compare x.from y.from
      | ordering -> ordering)

let equal a b = compare a b = 0

let to_string span =
  let region =
    if is_unknown span then unknown_file
    else if span.start.line = span.stop.line then
      if span.start.column = span.stop.column then string_of_position span.start
      else
        Printf.sprintf "%s:%d:%d-%d" span.start.file span.start.line
          span.start.column span.stop.column
    else
      Printf.sprintf "%s:%d:%d-%d:%d" span.start.file span.start.line
        span.start.column span.stop.line span.stop.column
  in
  match generators span with
  | [] -> region
  | names -> Printf.sprintf "%s (generated by %s)" region (String.concat " < " names)

let pp formatter span = Format.pp_print_string formatter (to_string span)
