(* Unit tests for the Core identity layer: spans, constants, and hygienic
   identifiers (to-do task 0.2). *)

open Ash_core

let failures = ref 0

let check name condition =
  if not condition then (
    incr failures;
    Printf.printf "FAIL %s\n" name)

let check_equal name ~printer ~equal expected actual =
  if not (equal expected actual) then (
    incr failures;
    Printf.printf "FAIL %s\n  expected: %s\n  actual:   %s\n" name
      (printer expected) (printer actual))

let check_string name expected actual =
  check_equal name ~printer:(fun s -> s) ~equal:String.equal expected actual

let check_int name expected actual =
  check_equal name ~printer:string_of_int ~equal:Int.equal expected actual

let check_raises_invalid_argument name thunk =
  match thunk () with
  | () ->
      incr failures;
      Printf.printf "FAIL %s\n  expected Invalid_argument, got normal return\n" name
  | exception Invalid_argument _ -> ()

let idents_to_string idents =
  "[" ^ String.concat "; " (List.map Ident.to_string idents) ^ "]"

let check_idents name expected actual =
  check_equal name ~printer:idents_to_string
    ~equal:(List.equal Ident.equal)
    expected actual

(* Spans *)

let pos file line column offset = Span.position ~file ~line ~column ~offset

let span file (l1, c1, o1) (l2, c2, o2) =
  Span.make ~start:(pos file l1 c1 o1) ~stop:(pos file l2 c2 o2)

let test_spans () =
  let a = span "fact.ash" (1, 1, 0) (1, 5, 4) in
  let b = span "fact.ash" (1, 9, 8) (2, 3, 14) in
  check_string "span.to_string single line" "fact.ash:1:1-5" (Span.to_string a);
  check_string "span.to_string multi line" "fact.ash:1:9-2:3" (Span.to_string b);
  check_string "span.to_string point" "fact.ash:1:1"
    (Span.to_string (Span.point (pos "fact.ash" 1 1 0)));
  check_string "span.to_string unknown" "<unknown>" (Span.to_string Span.unknown);
  check "span.is_unknown" (Span.is_unknown Span.unknown);
  check "span.is_unknown on real span" (not (Span.is_unknown a));
  check_string "span.file" "fact.ash" (Span.file a);

  (* join covers both operands, in either order, and absorbs unknown spans. *)
  let joined = Span.join a b in
  check_string "span.join covers both" "fact.ash:1:1-2:3" (Span.to_string joined);
  check "span.join is order insensitive on positions"
    (Span.equal joined (Span.join b a));
  check "span.join absorbs unknown on the left"
    (Span.equal a (Span.join Span.unknown a));
  check "span.join absorbs unknown on the right"
    (Span.equal a (Span.join a Span.unknown));

  (* A generated node keeps the user positions it came from, so diagnostics still
     point at real source, and additionally records who made it. *)
  let sugar = Span.generated ~by:"desugar/seq" ~from:a in
  check "span.generated is generated" (Span.is_generated sugar);
  check "span.generated keeps its origin positions"
    (Span.equal_position (Span.source_span sugar).start a.Span.start
    && Span.equal_position (Span.source_span sugar).stop a.Span.stop);
  check "span.source_span strips the marker" (Span.equal a (Span.source_span sugar));
  check "span.source_span is identity on source" (Span.equal a (Span.source_span a));
  check_string "span.to_string of generated" "fact.ash:1:1-5 (generated by desugar/seq)"
    (Span.to_string sugar);
  check "span.generators of source is empty" (Span.generators a = []);

  (* Provenance nests: the specializer emitting a node built by the desugarer must
     be able to report the whole chain. *)
  let staged = Span.generated ~by:"stage/let-insert" ~from:sugar in
  check "span.generators nests outermost first"
    (Span.generators staged = [ "stage/let-insert"; "desugar/seq" ]);
  check "span.source_span walks the whole chain"
    (Span.equal a (Span.source_span staged));
  check_string "span.to_string of nested generated"
    "fact.ash:1:1-5 (generated by stage/let-insert < desugar/seq)"
    (Span.to_string staged);

  (* Provenance is part of span equality: a generated node is not the same
     metadata as the source node it copied its positions from. *)
  check "span.equal distinguishes provenance" (not (Span.equal a sugar));
  check "span.compare distinguishes provenance" (Span.compare a sugar <> 0);
  check "span.compare is reflexive" (Span.compare staged staged = 0);
  check "span.compare orders by start" (Span.compare a b < 0);

  (* A join whose left side is generated keeps the nearest generator. *)
  check "span.join keeps a generated left origin"
    (Span.generators (Span.join sugar b) = [ "desugar/seq" ]);
  check "span.join adopts a generated right origin"
    (Span.generators (Span.join a sugar) = [ "desugar/seq" ]);

  (* Cross-file joins keep the node being built rather than inventing a region. *)
  let elsewhere = span "prelude.ash" (7, 1, 100) (7, 4, 103) in
  check "span.join across files keeps the left span"
    (Span.equal a (Span.join a elsewhere))

(* Constants *)

let test_constants () =
  check_string "constant Num" "42" (Constant.to_string (Constant.Num 42));
  check_string "constant negative Num" "-7" (Constant.to_string (Constant.Num (-7)));
  check_string "constant Bool true" "true" (Constant.to_string (Constant.Bool true));
  check_string "constant Bool false" "false" (Constant.to_string (Constant.Bool false));
  check_string "constant Str" "\"hi\"" (Constant.to_string (Constant.Str "hi"));
  check_string "constant Sym" "'zero" (Constant.to_string (Constant.Sym "zero"));
  check_string "constant Unit" "()" (Constant.to_string Constant.Unit);
  check_string "constant Nil" "[]" (Constant.to_string Constant.Nil);

  check_string "constant string escaping" "\"a\\\"b\\\\c\\nd\\te\\r\\x00f\""
    (Constant.escape_string "a\"b\\c\nd\te\r\x00f");

  check_string "type_name Num" "number" (Constant.type_name (Constant.Num 0));
  check_string "type_name Bool" "boolean" (Constant.type_name (Constant.Bool true));
  check_string "type_name Str" "string" (Constant.type_name (Constant.Str ""));
  check_string "type_name Sym" "symbol" (Constant.type_name (Constant.Sym "s"));
  check_string "type_name Unit" "unit" (Constant.type_name Constant.Unit);
  check_string "type_name Nil" "list" (Constant.type_name Constant.Nil);

  check "constant equal reflexive" (Constant.equal (Constant.Num 1) (Constant.Num 1));
  check "constant equal on Unit" (Constant.equal Constant.Unit Constant.Unit);
  check "constant equal on Nil" (Constant.equal Constant.Nil Constant.Nil);
  check "constant unequal same shape"
    (not (Constant.equal (Constant.Num 1) (Constant.Num 2)));
  (* Shapes never collapse into one another: a symbol is not its printed string,
     and Unit is not the empty list. *)
  check "constant symbol is not string"
    (not (Constant.equal (Constant.Sym "a") (Constant.Str "a")));
  check "constant unit is not nil" (not (Constant.equal Constant.Unit Constant.Nil));
  check "constant number is not boolean"
    (not (Constant.equal (Constant.Num 1) (Constant.Bool true)));

  let samples =
    [
      Constant.Nil;
      Constant.Unit;
      Constant.Sym "b";
      Constant.Sym "a";
      Constant.Str "z";
      Constant.Bool true;
      Constant.Bool false;
      Constant.Num 3;
      Constant.Num (-1);
    ]
  in
  let sorted = List.sort Constant.compare samples in
  check_string "constant compare sorts deterministically"
    "-1; 3; false; true; \"z\"; 'a; 'b; (); []"
    (String.concat "; " (List.map Constant.to_string sorted));
  check "constant compare agrees with equal"
    (List.for_all
       (fun x ->
         List.for_all
           (fun y -> Constant.equal x y = (Constant.compare x y = 0))
           samples)
       samples);
  check "constant compare is antisymmetric"
    (List.for_all
       (fun x ->
         List.for_all
           (fun y ->
             Int.compare (Constant.compare x y) 0
             = -Int.compare (Constant.compare y x) 0)
           samples)
       samples)

(* Hygienic identifiers *)

let test_idents () =
  let x1 = Ident.fresh "x" in
  let x2 = Ident.fresh "x" in
  let y = Ident.fresh "y" in

  (* The load-bearing property: printed name is not identity. *)
  check "same-name binders print alike" (Ident.same_name x1 x2);
  check "same-name binders are distinct" (not (Ident.equal x1 x2));
  check "fresh IDs differ" (Ident.id x1 <> Ident.id x2);
  check "identifier is equal to itself" (Ident.equal x1 x1);
  check "compare agrees with equal" (Ident.compare x1 x1 = 0);
  check "compare separates distinct binders" (Ident.compare x1 x2 <> 0);
  check_string "name accessor" "x" (Ident.name x1);
  check_string "to_string is unambiguous"
    (Printf.sprintf "x#%d" (Ident.id x1))
    (Ident.to_string x1);
  check "hash agrees with equality" (Ident.hash x1 = Ident.hash x1);

  let renamed = Ident.derive x1 in
  check "derive keeps the printed name" (Ident.same_name x1 renamed);
  check "derive allocates a new identity" (not (Ident.equal x1 renamed));
  let renamed_as = Ident.derive_as "tmp" x1 in
  check_string "derive_as takes the new name" "tmp" (Ident.name renamed_as);
  check "derive_as allocates a new identity" (not (Ident.equal x1 renamed_as));

  (* Collections key on identity, so two same-name binders coexist. *)
  let set = Ident.Set.of_list [ x1; x2; y; x1 ] in
  check_int "set keeps same-name binders apart" 3 (Ident.Set.cardinal set);
  let map = Ident.Map.(empty |> add x1 "outer" |> add x2 "inner") in
  check_string "map keeps same-name binders apart" "outer" (Ident.Map.find x1 map);
  check_string "map second same-name binding" "inner" (Ident.Map.find x2 map)

(* Canonicalization: alpha-renaming collapses, distinct binders do not. *)

let test_canonicalization () =
  (* Two occurrence sequences with the same shape but unrelated names and IDs:
     fn(x) -> fn(z) -> x z x, written out as its identifier occurrences. *)
  let x = Ident.fresh "x" and z = Ident.fresh "z" in
  let sample = [ x; z; x; z; x ] in
  let a = Ident.fresh "a" and b = Ident.fresh "b" in
  let renamed = [ a; b; a; b; a ] in
  check_idents "alpha-renamed samples canonicalize equal"
    (Ident.Canon.list sample) (Ident.Canon.list renamed);

  (* Allocation order is an excluded observation: interleaving unrelated fresh
     identifiers must not change any canonical result. *)
  let _noise = List.init 17 (fun i -> Ident.fresh (Printf.sprintf "noise%d" i)) in
  let c = Ident.fresh "x" and d = Ident.fresh "q" in
  check_idents "canonicalization ignores allocation order"
    (Ident.Canon.list sample)
    (Ident.Canon.list [ c; d; c; d; c ]);

  (* Same printed name, different binders: canonicalization must keep them apart,
     otherwise shadowing would be erased. *)
  let outer = Ident.fresh "x" and inner = Ident.fresh "x" in
  let shadowing = Ident.Canon.list [ outer; inner; outer ] in
  let non_shadowing = Ident.Canon.list [ outer; outer; outer ] in
  check "same-name different-ID binders stay distinct"
    (not (List.equal Ident.equal shadowing non_shadowing));
  check_idents "shadowing canonicalizes by first occurrence"
    (Ident.Canon.list [ x; z; x ])
    shadowing;

  (* Canonical results are stable and idempotent within one state. *)
  let state = Ident.Canon.create () in
  let first = Ident.Canon.canonical state x in
  let again = Ident.Canon.canonical state x in
  check "canonical is stable within a state" (Ident.equal first again);
  check "canonicalizing a canonical sequence changes nothing"
    (List.equal Ident.equal (Ident.Canon.list sample)
       (Ident.Canon.list (Ident.Canon.list sample)));
  check_int "count tracks distinct identifiers" 1 (Ident.Canon.count state);
  ignore (Ident.Canon.canonical state z);
  check_int "count grows per distinct identifier" 2 (Ident.Canon.count state);
  (* Canonical identities occupy their own numbering, counting down from -1
     while allocated ones count up from 1, so a canonical binder can never
     collide with a free identifier that happens to print the same. *)
  check_int "canonical slots are numbered from minus one" (-1) (Ident.id first);
  check_string "erased names are positional" "v" (Ident.name first);
  check "canonical identities never collide with allocated ones"
    (List.for_all
       (fun ident -> Ident.id ident < 0)
       (Ident.Canon.list [ x; z; Ident.fresh "v" ]));
  check "an allocated identity is never negative" (Ident.id (Ident.fresh "v") > 0);

  (* Free identifiers must be reserved before traversal, or two different free
     variables would both canonicalize to the first slot. *)
  let free_x = Ident.fresh "x" and free_y = Ident.fresh "y" in
  let with_fix free term =
    let state = Ident.Canon.create () in
    List.iter (Ident.Canon.fix state) free;
    List.map (Ident.Canon.canonical state) term
  in
  check "fixed identifiers survive canonicalization"
    (List.equal Ident.equal [ free_x; free_y ] (with_fix [ free_x; free_y ] [ free_x; free_y ]));
  check "distinct free identifiers stay distinct"
    (not
       (List.equal Ident.equal
          (with_fix [ free_x ] [ free_x ])
          (with_fix [ free_y ] [ free_y ])));
  let mixed_state = Ident.Canon.create () in
  Ident.Canon.fix mixed_state free_x;
  let bound = Ident.Canon.canonical mixed_state x in
  check "fixing does not consume a canonical slot" (Ident.id bound = -1);
  check_int "fixed identifiers are excluded from the count" 1
    (Ident.Canon.count mixed_state);
  check_raises_invalid_argument "fix rejects an already canonicalized identifier"
    (fun () -> Ident.Canon.fix mixed_state x);
  check_raises_invalid_argument "fix rejects a double fix" (fun () ->
      Ident.Canon.fix mixed_state free_x)

let () =
  test_spans ();
  test_constants ();
  test_idents ();
  test_canonicalization ();
  if !failures > 0 then (
    Printf.printf "%d core unit assertion(s) failed\n" !failures;
    exit 1)
