(* Unit tests for structured errors (to-do task 0.4). *)

open Ash_core

let failures = ref 0

let check name condition =
  if not condition then (
    incr failures;
    Printf.printf "FAIL %s\n" name)

let check_string name expected actual =
  if not (String.equal expected actual) then (
    incr failures;
    Printf.printf "FAIL %s\n  expected: %s\n  actual:   %s\n" name expected actual)

let check_int name expected actual =
  if not (Int.equal expected actual) then (
    incr failures;
    Printf.printf "FAIL %s\n  expected: %d\n  actual:   %d\n" name expected actual)

let distinct strings =
  List.length (List.sort_uniq String.compare strings) = List.length strings

let span =
  Span.make
    ~start:(Span.position ~file:"demo.ash" ~line:12 ~column:3 ~offset:200)
    ~stop:(Span.position ~file:"demo.ash" ~line:12 ~column:8 ~offset:205)

let phases =
  [ Error.Read; Error.Lex; Error.Parse; Error.Desugar; Error.Evaluate; Error.Stage; Error.Collapse ]

let x = Ident.fresh "x"
let x' = Ident.fresh "x"

let causes =
  [
    Error.Unbound_ident x;
    Error.Unbound_name "x";
    Error.Ambiguous_name { name = "x"; candidates = [ x; x' ] };
    Error.Unfilled_binding x;
    Error.Unexpected_character '@';
    Error.Unterminated "string literal";
    Error.Unexpected { found = "an integer"; expected = "a Core form" };
    Error.Unknown_form "lambda";
    Error.Malformed_form { form = "lam"; expected = "(lam (param ...) body)" };
    Error.Arity_error { callee = Some "f"; expected = "2"; actual = 3 };
    Error.Unsupported { what = "quote"; by = "the direct-style oracle" };
    Error.Division_by_zero;
    Error.Duplicate_binder "x";
    Error.Inconsistent_pattern_binders { expected = [ "x" ]; actual = [ "y" ] };
    Error.End_of_input;
  ]

let test_phases () =
  check_int "every phase is enumerated" 7 (List.length phases);
  check "phase names are distinct" (distinct (List.map Error.phase_name phases));
  check_string "the evaluate phase is named" "evaluate" (Error.phase_name Error.Evaluate)

let test_causes () =
  check_int "every cause is enumerated" 15 (List.length causes);
  check "cause messages are distinct" (distinct (List.map Error.cause_message causes));
  List.iter
    (fun cause ->
      check "every cause has a message" (String.length (Error.cause_message cause) > 0))
    causes;
  check_string "an ambiguous name reports how many candidates there are"
    "the name `x` is bound 2 times in one frame, so a name lookup cannot choose"
    (Error.cause_message (Error.Ambiguous_name { name = "x"; candidates = [ x; x' ] }))

let test_rendering () =
  let error = Error.make ~phase:Error.Evaluate ~span (Error.Unbound_ident x) in
  check_string "an error renders phase, location and cause"
    "demo.ash:12:3-8: evaluate error: unbound identifier `x`" (Error.to_string error);
  let levelled = Error.make ~phase:Error.Evaluate ~span ~level:2 (Error.Unbound_ident x) in
  check_string "a levelled error says which level"
    "demo.ash:12:3-8: evaluate error at level 2: unbound identifier `x`"
    (Error.to_string levelled);
  check "an error with no level says nothing about levels"
    (error.Error.level = None);

  (* Unique IDs are an excluded observation: a rendered diagnostic must not
     depend on allocation order, or golden output becomes unstable. Two distinct
     binders that print alike therefore render identically, and only the debug
     form tells them apart. *)
  let other = Error.make ~phase:Error.Evaluate ~span (Error.Unbound_ident x') in
  check_string "same-name binders render identically" (Error.to_string error)
    (Error.to_string other);
  check "the debug form distinguishes them"
    (not (String.equal (Error.to_string_debug error) (Error.to_string_debug other)));
  check "the debug form carries the ID"
    (String.equal
       (Printf.sprintf "demo.ash:12:3-8: evaluate error: unbound identifier `%s`"
          (Ident.to_string x))
       (Error.to_string_debug error));

  (* Generated provenance travels into diagnostics through the span. *)
  let emitted =
    Error.make ~phase:Error.Stage
      ~span:(Span.generated ~by:"stage/let-insert" ~from:span)
      (Error.Unbound_ident x)
  in
  check_string "a diagnostic on generated code names the phase that made it"
    "demo.ash:12:3-8 (generated by stage/let-insert): stage error: unbound identifier `x`"
    (Error.to_string emitted)

let test_raising () =
  let raised =
    match Error.raise_cause ~phase:Error.Read ~span ~level:0 (Error.Unbound_name "q") with
    | () -> None
    | exception Error.Ash_error error -> Some error
  in
  check "raise_cause raises a structured error"
    (match raised with
    | Some error ->
        error.Error.phase = Error.Read
        && error.Error.level = Some 0
        && Span.equal span error.Error.span
        && Error.cause_equal error.Error.cause (Error.Unbound_name "q")
    | None -> false);
  let failed =
    let error = Error.make ~phase:Error.Parse ~span (Error.Unbound_name "q") in
    match Error.fail error with
    | _ -> false
    | exception Error.Ash_error raised -> raised == error
  in
  check "fail raises the very error it was given" failed

let test_equality () =
  (* Differential tests compare reported failures structurally, so rewording a
     message must not change what a comparison asserts. *)
  check "a cause equals itself"
    (List.for_all (fun cause -> Error.cause_equal cause cause) causes);
  check "distinct causes are unequal"
    (not (Error.cause_equal (Error.Unbound_name "x") (Error.Unknown_form "x")));
  check "causes of the same shape compare their payloads"
    (not (Error.cause_equal (Error.Unterminated "list") (Error.Unterminated "string literal")));
  check "same-name different-identity binders are different causes"
    (not (Error.cause_equal (Error.Unbound_ident x) (Error.Unbound_ident x')));
  let base = Error.make ~phase:Error.Read ~span (Error.Unknown_form "lam") in
  check "an error equals itself" (Error.equal base base);
  check "the phase is part of the error"
    (not (Error.equal base (Error.make ~phase:Error.Parse ~span (Error.Unknown_form "lam"))));
  check "the level is part of the error"
    (not (Error.equal base (Error.make ~phase:Error.Read ~span ~level:0 (Error.Unknown_form "lam"))));
  check "the span is part of the error"
    (not
       (Error.equal base
          (Error.make ~phase:Error.Read ~span:Span.unknown (Error.Unknown_form "lam"))))

let () =
  test_phases ();
  test_equality ();
  test_causes ();
  test_rendering ();
  test_raising ();
  if !failures > 0 then (
    Printf.printf "%d error assertion(s) failed\n" !failures;
    exit 1)
